- src/StreamSelectLoop.php
- tests/AbstractLoopTest.php
- tests/StreamSelectLoopTest.php
This PR contains a test case for #20 as requested by @clue and @WyriHaximus. I have also applied the fix by @mkrauser to make the tests pass.
This fixes the issue described in reactphp/react#296.
The test sets up an event loop and then forks a child process which will send a signal to the current process while it is waiting for stream_select(). This triggers stream_select() to return false and throw a warning.
The test currently uses error_reporting to suppress this warning as in the issue discussion the supression of the warning with `@` was no wanted. I think there should be a benchmark to check if adding an `@` to stream select has any negative effect. I doubt it.
>  check return value of stream_select including a test case

- .travis.yml
- src/ExtEventLoop.php
- src/LibEventLoop.php
- tests/AbstractLoopTest.php
- tests/StreamSelectLoopTest.php
- travis-init.sh
- there is no `hhvm-nightly` anymore on travis https://github.com/travis-ci/travis-ci/issues/3788#issuecomment-97171678
- add php 7
- `event` extension works
- `libev` does not support PHP 7 (yet?) https://github.com/m4rw3r/php-libev/issues/8
- `libevent` also does not support PHP 7 https://pecl.php.net/package/libevent
- applied patch by @ondrejmirtes from #39 to make tests pass
> [WIP] Update .travis.yml for PHP 7

- LibEventLoop.php
- Timer/Timer.php
- Timer/Timers.php
This change only aims to improve compatibility with v0.4 which already has the same behavior: https://github.com/reactphp/event-loop/blob/164799f73175e1c80bba92a220ea35df6ca371dd/src/Timer/Timer.php#L9
Currently (v0.3 only), when passing an interval smaller than 1ms, we will throw an `InvalidArgumentException`.
With this change applied, the minimum timer interval is capped at 1µs. This means that passing any smaller interval will still try to execute the timer in 1µs.
There are quite a few libraries that target both v0.3 and v0.4 of this component, so it makes sense to keep BC breaks between those versions to a minimum. I'll look into linking relevant tickets against this PR.
FWIW: No tests included because the v0.3 branch does not currently contain any tests unfortunately.
> Cap min timer interval at 1µs, thus improving compatibility with v0.4

- tests/TestCase.php
The method `getMock()` was deprecated with the [release of PHPUnit 5.4](https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-5.4.0). The same release introduced `createMock()` that should be used to create mock objects instead. This PR modifies `React\Tests\EventLoop\TestCase::createCallableMock()` to use the new mock API if available.
> Avoid deprecation warnings in test suite due to deprecation of getMock() in PHPUnit

- tests/AbstractLoopTest.php
- tests/StreamSelectLoopTest.php
Currently, HHVM regularly causes (unrelated) tests failures in several of the existing PRs due to tight timeout values for our test suite.
This simple patch increases test timeouts for HHVM only and unifies timeout handling across all tests.
> Increase test timeouts for HHVM and unify timeout handling

- CHANGELOG.md
- src/ExtEventLoop.php
- src/LibEvLoop.php
- src/LibEventLoop.php
- src/LoopInterface.php
- src/StreamSelectLoop.php
- tests/AbstractLoopTest.php
- tests/ExtEventLoopTest.php
- tests/TestCase.php
- tests/Timer/AbstractTimerTest.php
References: https://github.com/reactphp/event-loop/pull/52#issuecomment-239688446, async-interop/event-loop#9
For the tests, i've added a [helper function](https://github.com/reactphp/event-loop/pull/72/files#diff-d4c8c6dc8769324fc27cfdac19f05cafR44) to `TestCase`.
Closes #52
> Drop tick() from LoopInterface

- .travis.yml
- travis-init.sh
Main changes are:
* Enabled running tests on travis' container based infrastructure
This solves that tests can now be run for forks which default to the container based infrastructure when created after 2015.
Refs:
* https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
* See eg. https://travis-ci.org/jsor/event-loop/jobs/198781026#L158, builds are failing here
* `composer install`
* Moved from travis-init.sh to .travis.yml
* Removed deprecated `--dev` option
* Removed `--prefer-source` not longer required to prevent rate limit issues, see https://github.com/composer/composer/issues/4884#issuecomment-195229989
* Run tests on PHP 7.1
> Travis improvements

- .travis.yml
- travis-init.sh
This contains all changes from #74 by @jsor squashed into a single commit for the 0.4 release branch:
* Remove deprecated --dev option from composer install
* Remove --prefer-source from composer install
* Move composer install to .travis.yml
* Enable container based infrastructure on travis
* Enable travis cache
* Add PHP 7.1 to test matrix
* Adjust composer cache directory to only cache package files
> Travis improvements (backported from #74)

- tests/AbstractLoopTest.php
- tests/ExtEventLoopTest.php
- tests/StreamSelectLoopTest.php
~~This PR contains 2 changes:~~
~~Warnings when using undefined signal constants in a PHPUnit data provider are avoided. Missing constants for signals are defined as needed in the abstract test case.~~
Streams used by test cases are created as connected socket pairs. Most event loop extension do not support arbitrary file descriptors but they all support socket pairs. The created socket pairs use unix domain sockets if they are available. The fallback to INET sockets is needed in order to support Windows.
> Test suite now uses socket pairs instead of memory streams

- appveyor.yml
#71 made me realize that we don't test on windows, this PR adds the configuration to do that.
> Run tests on windows using AppVeyor

- tests/StreamSelectLoopTest.php
Define constants `SIGUSR1`, `SIGHUP` and `SIGTERM` if they are not defined yet. The signal constants are used in data provider `StreamSelectLoopTest::signalProvider()` and cause a notice when the pcntl extension is not loaded.
```
Notice: Use of undefined constant SIGUSR1 - assumed 'SIGUSR1'
```
> StreamSelectLoop: Test suite uses signal constant names in data provider

- src/ExtEventLoop.php
- tests/AbstractLoopTest.php
- tests/ExtEventLoopTest.php
- tests/StreamSelectLoopTest.php
Adds #65, #66 and #67 from 0.4 to master.
> Update master from 0.4

- src/LibEvLoop.php
- tests/AbstractLoopTest.php
This tests the current behavior. I think the behavior should be changed to throw an exception instead of silently ignoring those callables or just call both callables.
> Add tests for double watchers to be ignored

- README.md
* Separate into sections and add a TOC at the beginning
* Add new sections for Install, Tests and License
* Add paragraph to Usage emphasizing on recommended program structuring using a single loop instance
> Restructure and improve README

- src/StreamSelectLoop.php
- tests/StreamSelectLoopTest.php
Resolving https://github.com/reactphp/event-loop/issues/48.
> StreamSelectLoop: Fix erroneous zero-time sleep (2)

- README.md
- examples/03-ticks.php
- examples/91-benchmark-ticks.php
- examples/92-benchmark-timers.php
- examples/93-benchmark-ticks-delay.php
- examples/94-benchmark-timers-delay.php
- src/LoopInterface.php
> Documentation and examples for deferred execution via futureTick()

- README.md
- src/ExtEventLoop.php
- src/LibEvLoop.php
- src/LibEventLoop.php
- src/LoopInterface.php
- src/StreamSelectLoop.php
- src/Timer/Timer.php
- src/Timer/TimerInterface.php
- src/Timer/Timers.php
- tests/Timer/AbstractTimerTest.php
- tests/Timer/TimersTest.php
The timer API is currently entirely undocumented and offers several duplicate methods and accessors not really *required*. Arguably, this makes the timer API appear more difficult than it actually is. The loop accessors also causes an unneeded cyclic dependency which hinders garbage collection. 
This PR adds documentation for the existing timer API and then subsequently removes unneeded methods and the cyclic dependency. Note that while this PR does remove parts of the existing API, it does not add any new APIs or otherwise modify the existing APIs. While this does contain some BC breaks, many consumers will not be affected by this due to the duplicate methods. This PR ensures to provide some upgrade guides to those affected by the BC breaks.
Performance improvement is not a major …
> Documentation for timer API and clean up unneeded timer API

- README.md
- examples/91-benchmark-ticks.php
- examples/93-benchmark-ticks-delay.php
- examples/94-benchmark-timers-delay.php
- src/ExtEventLoop.php
- src/LibEvLoop.php
- src/LibEventLoop.php
- src/LoopInterface.php
- src/StreamSelectLoop.php
- src/Tick/FutureTickQueue.php
- tests/AbstractLoopTest.php
The tick API has been documented as part of #100, however it makes no mention of how the tick function should look like. It actually currently receives the loop instance, which is entirely undocumented. The loop parameter also causes an unneeded cyclic dependency which hinders garbage collection.
This simple PR changes it so that the tick callback no longer receives a loop argument. This is obviously a small BC break, so this PR ensures to provide some upgrade guides to those affected by this. This is now also in line with the timer API, see #102.
Builds on top of #100 and refs #102
```php
// old (loop passed as parameter)
$loop->futureTick(function ($loop) {
$loop->stop();
});
// already supported before: use closure binding as usual
$loop->futureTick(function () use ($loop) { …
```
> Tick callback receives no arguments, fix cyclic dependency

- examples/95-benchmark-memory.php
- examples/test-memory.php
Originally from: https://github.com/reactphp/react/blob/master/examples/test-memory.php
Example output:
> Added enhanced test-memory.php, originally from react/react

- src/Factory.php
- src/LibEventLoop.php
The libevent extension has not been updated for PHP 7 and I have seen reports of segfaults as a result.
> Discourage libevent on PHP 7

- tests/StreamSelectLoopTest.php
Noticed some spurious test failures while working on #62 and #110 earlier today both locally and on Travis. This can easily be reproduced by running with `phpunit --repeat 100` and is now successfully worked around by increasing test timeouts.
> Make signal handling tests more robust and increase test timeouts

- README.md
- src/ExtEventLoop.php
- src/LibEvLoop.php
- src/LibEventLoop.php
- src/LoopInterface.php
- src/StreamSelectLoop.php
- tests/StreamSelectLoopTest.php
The stream API is currently mostly undocumented. This PR adds documentation for the existing stream API and then subsequently removes the unneeded and undocumented loop argument that was previously passed to stream listeners.
This is a subtle BC break. Empirical evidence (including our examples, tests and other components) suggest that most consumers will not be affected by this. The added documentation ensures that we now follow a strict API and will not introduce a BC break in the future.
Trying to create documentation for this API is not exactly trivial, as it's very low-level and has existed in this form almost since its inception. Given that most consumers SHOULD NOT use this API at all, I've marked the stream API as advanced and linked to the Stream component instead.
Performance …
> Documentation for advanced stream API

- composer.json
Our suggests are rather simple, IMHO it would look better if we suggest change the suggested extensions for which loop implementation they are.
> Improve Composer suggest description to detail for which loop implementation they are

- README.md
- composer.json
- examples/04-signals.php
- src/ExtEventLoop.php
- src/LibEvLoop.php
- src/LibEventLoop.php
- src/LoopInterface.php
- src/SignalsHandler.php
- src/StreamSelectLoop.php
- tests/AbstractLoopTest.php
- tests/SignalsHandlerTest.php
- tests/bootstrap.php
This PR adds OS signal handling. There are a few things of discussion, I'll post comments on the representing code lines.
Signal handlers:
> Add support for signal handling

- README.md
- examples/21-http-server.php
- src/ExtEventLoop.php
- src/LibEvLoop.php
- src/LibEventLoop.php
- src/LoopInterface.php
- src/StreamSelectLoop.php
- tests/AbstractLoopTest.php
The `removeStream()` acts as a shortcut to essentially call both `removeReadStream()` and `removeWriteStream()` in one go. It's unclear how much value this method actually provides and it looks like this has attracted some low quality code in the past. As such, I'm filing this PR as an RFC to see if it makes sense to drop this unneeded method.
Refs #110
> [RFC] Remove removeStream() method, use removeReadStream/removeWriteStream instead

- composer.json
- tests/StreamSelectLoopTest.php
- tests/TestCase.php
I use the `PHPUnit\Framework\TestCase` notation instead of `PHPUnit_Framework_TestCase` while extending our TestCase. This will help us migrate to PHPUnit 6, that [no longer support snake case class names](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).
I just need to bump PHPUnit version to [`~4.8.35`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.8.md#4835---2017-02-06), that support this namespace.
> Forward compatibility with PHPUnit 6 and PHPUnit 5

- src/ExtEventLoop.php
- tests/AbstractLoopTest.php
It has come to our attention that certain loop implementations do not keep track of assigned stream resources (refcount). This means that stream resources may be garbage collected despite being added to the loop when leaving the scope where they have been defined. Arguably, this is a design decision that makes sense for a number of PHP extension modules.
This issue is implicitly avoiding by using react/stream, which stores the stream resource in a member variable and thus prevents garbage collection. This means that this is not an issue for most people that rely on this component. However, this issue can be exhibited quite easily by using the EventLoop directly.
Given that our loop interface tries to abstract these underlying differences, we may have to keep track of stream resources …
> Fix ExtEventLoop to keep track of stream resources (refcount)

- README.md
- src/ExtEventLoop.php
- src/LibEvLoop.php
- src/LibEventLoop.php
- src/LoopInterface.php
- src/StreamSelectLoop.php
- tests/AbstractLoopTest.php
Builds on top of #119, #125 and others.
> Minor documentation improvements

- README.md
- composer.json
- src/ExtLibevLoop.php
- src/ExtLibeventLoop.php
- src/Factory.php
- tests/ExtLibevLoopTest.php
- tests/ExtLibeventLoopTest.php
- tests/Timer/ExtLibevTimerTest.php
- tests/Timer/ExtLibeventTimerTest.php
This simple PR ensure we use a consistent naming scheme for all event loop implementations.
* rename `LibEventLoop` to `ExtLibeventLoop` (`ext-libevent`) and
* rename`LibEvLoop` to `ExtLibevLoop` (`ext-libev`),
* keep `ExtEventLoop` (`ext-event`),
* keep `StreamSelectLoop` (does not require an extension).
Resolves / closes #115
Builds on top of #127
> Consistent naming for event loop implementations

- src/ExtEventLoop.php
- src/ExtLibevLoop.php
- src/ExtLibeventLoop.php
- src/Factory.php
- src/StreamSelectLoop.php
Classes should be used via composition rather than extension.
This reduces our API footprint and avoids future BC breaks by avoiding
exposing its internal assumptions.
Builds on top of #128
> Mark all classes as final to discourage inheritance

- README.md
- src/ExtEventLoop.php
- src/ExtLibevLoop.php
- src/ExtLibeventLoop.php
- src/LoopInterface.php
- src/StreamSelectLoop.php
- tests/Timer/AbstractTimerTest.php
> Remove unneeded isTimerActive() to reduce API surface

- src/ExtEventLoop.php
- src/ExtLibeventLoop.php
- tests/AbstractLoopTest.php
~~~Filing this as WIP in order to create a reproducible test first and will fix this in a subsequent commit.~~~
Resolves / closes #136
> Fix separately removing readable and writable side of stream when closing

- src/ExtEventLoop.php
- src/ExtLibevLoop.php
- src/ExtLibeventLoop.php
- src/LoopInterface.php
- src/SignalsHandler.php
- src/StreamSelectLoop.php
- src/Tick/FutureTickQueue.php
- src/Timer/Timer.php
I'm filing this PR as an RFC to see if it makes sense to drop these type hints.
> [RFC] Remove all callable type hints for consistency and performance reasons

- examples/95-benchmark-memory.php
> Fix memory benchmark

- tests/AbstractLoopTest.php
- tests/Timer/AbstractTimerTest.php
- tests/Timer/TimersTest.php
This simple PR improves the test suite to use less fragile assumptions for the timer tests and avoids related warnings about "risky" tests by PHPUnit.
The old test suite works fine on Travis, but reports these "risky" tests. For some reason, the test suite failed on my local machine when using `ext-event`, despite using same PHP version, same PECL version and same composer packages as seen on Travis: https://gist.github.com/clue/8216c7494769d31dd0c6279a0a27ed7b
The updated test suite avoids blocking the loop and thus makes these tests less fragile.
Builds on top of #138 and #120
> Improve test suite to be less fragile

- src/ExtEventLoop.php
- src/ExtLibevLoop.php
> Properly clean up event watchers for ext-event and ext-libev

- src/ExtEventLoop.php
- src/ExtLibevLoop.php
- src/ExtLibeventLoop.php
- src/SignalsHandler.php
- src/StreamSelectLoop.php
- tests/AbstractLoopTest.php
- tests/SignalsHandlerTest.php
This PR refactors some of the internal signal handling logic. It avoids a number of circular references to avoid relying on GC collecting cycles. It does not affect the public API, this is internal only.
Builds on top of #104 and #149
> Refactor and simplify signal handling logic

- .travis.yml
- README.md
- composer.json
- src/ExtEventLoop.php
- src/ExtLibevLoop.php
- src/ExtLibeventLoop.php
- src/SignalsHandler.php
- src/StreamSelectLoop.php
- tests/AbstractLoopTest.php
- tests/StreamSelectLoopTest.php
- travis-init.sh
Because _why not_… :-)
Now more seriously: This project is a low level lib that is used as a building block for quite a few higher level abstractions on top of it. As such, compatibility (even with significantly outdated versions) is a major concern to me.
Note that I'm not suggesting putting _significant amount_ of work into this. The patch is already here and, personally, I see little harm in supporting this.
Also note that I'm not suggesting we need to keep support indefinitely. Should this ever turn out to be a burden in the future, e.g. because we actually _require_ any new language features or some external lib, then I'm all for dropping support again. If you want to discuss this further, I would suggest directing this to https://github.com/reactphp/react/issues/374 instead 👍
> [RFC] Improve compatibility with legacy versions

- tests/AbstractLoopTest.php
Travis and other CIs run slower than one might think.
See https://travis-ci.org/amphp/react-adapter/jobs/216294364#L211.
> Increase test timeout, because Travis is slow

- src/ExtEventLoop.php
- tests/ExtEventLoopTest.php
Mutually exclusive with #154
This came up in a discussion after #154 was filed and because doing this by default will be provide a better BC.
> ExtEventLoop: Remove optional EventBaseConfig and make FEATURE_FDS enabled by default

- README.md
- src/ExtEventLoop.php
- src/ExtLibevLoop.php
- src/ExtLibeventLoop.php
This came up during our [hangouts call today](https://twitter.com/WyriHaximus/status/968594002474946560). At the moment when creating a loop directly when the required extension is missing creating will fail epicly. This proposed PR will throw an `BadMethodCallException` when the required extension is missing.
> Throw BadMethodCallException on manual loop creating when required extension isn't installed

- composer.json
I agree that we want to suggest installing event loop extensions for some use cases (this is covered in #127). However, we probably do not want to suggest installing outdated event loop extensions that are no longer supported on PHP 7. These are a constant source of confusion as they're known to cause SEGFAULTs. This simple PR removes these outdated suggestions.
Builds on top of #127
Resolves / closes #114
> Do not suggest installing outdated event loop extensions

- README.md
- src/LoopInterface.php
This very simple PR adds documentation to make consumers aware that `addReadStream()` and `addWriteStream()` *MAY* throw an `Exception` if the given stream resource type is not supported by the underlying event loop implementation. This is explicitly not *enforced* due to performance considerations, so consumers SHOULD NOT rely on this.
Builds on top of #110
> Allow throwing Exception if stream resource is not supported

- tests/AbstractLoopTest.php
As discussed [here](https://github.com/reactphp/event-loop/issues/146) this PR reduces the string length to be written during the test to one single default chunk in order to avoid blocking calls and as well the `EAGAIN` error at MacOS devices.
> Reduces fwrite() call length to one chunk

- README.md
- src/LoopInterface.php
This simple PR adds documentation for the existing `run()` and `stop()` method behavior.
Builds on top of #100, #102 and others.
> Documentation for run() and stop()

- README.md
- src/ExtEvLoop.php
- src/Factory.php
- tests/ExtEvLoopTest.php
- tests/Timer/AbstractTimerTest.php
- tests/Timer/ExtEvTimerTest.php
- travis-init.sh
@clue, @WyriHaximus, @jsor hello!
Finally I fixed my old [pull request](https://github.com/reactphp/event-loop/pull/97). I'm really sorry that it took so long for me.
I hope, that this feature still wanted and needed :)
> Implement ExtEvLoop (PECL ext-ev)

- src/Timer/Timers.php
While debugging some very *odd memory issues* in a live application, I noticed that the `StreamSelectLoop` does not immediately free all related memory when a timer is cancelled. Let's not call this a "memory leak", because memory was *eventually* freed, but this clearly caused some unexpected and significant memory growth.
In many common programs, adding timeouts to operations is a very fundamental operation. As such, it's common to end up with hundred or thousands of timers which most of the time get cancelled very frequently as a successful execution will quickly cancel outstanding timeouts.
I've used the following script to demonstrate unreasonable memory growth:
```
<?php
use React\EventLoop\Factory;
require __DIR__ . '/../vendor/autoload.php';
$loop = Factory::create(); …
```
> StreamSelectLoop: Improve memory consumption and runtime performance for timers

- tests/AbstractLoopTest.php
https://github.com/reactphp/event-loop/issues/162
> Removes I/O dependency at StreamSelectLoopTest to fix Mac OS X tests

- src/ExtEvLoop.php
- src/ExtEventLoop.php
- src/ExtLibevLoop.php
- src/ExtLibeventLoop.php
- src/Factory.php
- src/SignalsHandler.php
- src/StreamSelectLoop.php
- src/Tick/FutureTickQueue.php
- src/Timer/Timers.php
- tests/Timer/TimersTest.php
This keeps me awake for now. Silly patch, still kinda relevant for this low-level component
Note that I wanted to use `doctrine/coding-standard` on it, but the package seems to still support PHP 5.3 (!!!!!!!!!!!!!!!!!!).
> Imported global functions

- src/StreamSelectLoop.php
This PR makes it possible to use PCNTL's asynchronous signal dispatching, if PHP 7.1 or higher is used. This allows to dispatch signals anywhere, without any overhead. This also means signals can be handled faster and more efficient, without having to rely on the manual dispatch on each tick.
RFC for async signals dispatching: https://wiki.php.net/rfc/async_signals
> Add pcntl async signal dispatching if available

- README.md
- src/LoopInterface.php
- src/StreamSelectLoop.php
- src/Timer/Timers.php
This project suggests that event loop implementations SHOULD use a
monotonic time source if available. Given that a monotonic time source is
only available as of PHP 7.3 by default, event loop implementations MAY
fall back to using wall-clock time. http://php.net/manual/en/function.hrtime.php
Builds on top of #157 and #130
Resolves #73
> Use high resolution timer on PHP 7.3+ 

- src/StreamSelectLoop.php
> Fix high CPU usage when only listening for signals with default loop

- src/StreamSelectLoop.php
This helps avoiding problems when the PCNTL extension is loaded, but
(some of) its functions are disabled via PHPs `disable_function`
configuration. This is particularly common for the PCNTL functions in
CGI environments, e.g. they are disabled by default on Debian- /
Ubuntu-based distributions. Previously, even when not attaching any
signal listeners, the loop would print a warning on each loop tick:
> PHP Warning:  pcntl_signal_dispatch() has been disabled for security
reasons in {file} on {line}
Builds on top of #179
> Check PCNTL functions for signal support instead of PCNTL extension

- .travis.yml
- travis-init.sh
For some reason `libuv1-dev` isn't available anymore on Travis. Had to shuffle the Ubuntu distro's around a bit to get it working again. Also enabled `ext-uv` testing on PHP 7.3 while I was at it.
> Fix testing ext-uv on Travis

- src/ExtUvLoop.php
- tests/AbstractLoopTest.php
- tests/ExtUvLoopTest.php
- tests/Timer/AbstractTimerTest.php
This PR fixes https://github.com/reactphp/event-loop/issues/194.
> Prevent "interval" overflow in ExtUvLoop

- .travis.yml
Builds on top of #197 and https://github.com/clue/reactphp-ami/commit/bfc91b7fe9674291fa5cf85612ef2e273203a8cf
Noticed due to unrelated build error in #201
> Fix Travis CI builds, do not install libuv on legacy PHP setups

- tests/Timer/AbstractTimerTest.php
Builds on top of #202 and others.
> Fix failing test cases due to inaccurate timers

- .travis.yml
- src/ExtEventLoop.php
Resolves #189 
Supersedes / closes #192, thanks @inri13666 for the initial version!
Builds on top of #204
> Fix unsupported EventConfig and SEGFAULTs on shutdown for ext-event on Windows

- .travis.yml
- src/ExtUvLoop.php
- tests/AbstractLoopTest.php
This PR fixes reporting "connection refused" on affected installation of ExtUvLoop. I have started with adding relevant tests to the test matrix, fixing the underlying issue and included additional tests to run run this on Windows as well.
Resolves #188
Builds on top of #205
Refs #206 to skip a similar problem for the `StreamSelectLoop` on Windows only.
> ExtUvLoop: Fix reporting connection refused errors

- .travis.yml
- src/ExtUvLoop.php
- src/StreamSelectLoop.php
- tests/AbstractLoopTest.php
We do not usually use or expose the `exceptfds` parameter passed to the
underlying `select`. However, Windows does not report failed connection
attempts in `writefds` passed to `select` like most other platforms.
Instead, it uses `writefds` only for successful connection attempts and
`exceptfds` for failed connection attempts. See also
https://docs.microsoft.com/de-de/windows/win32/api/winsock2/nf-winsock2-select
We work around this by adding all sockets that look like a pending
connection attempt to `exceptfds` automatically on Windows and merge it
back later. This ensures the public API matches other loop
implementations across all platforms (see also test suite or rather test
matrix). Lacking better APIs, every write-only socket that has not yet
read any data is assumed to be in a …
> Fix reporting refused connections with StreamSelectLoop on Windows

- .travis.yml
- src/ExtUvLoop.php
- src/StreamSelectLoop.php
- tests/AbstractLoopTest.php
- travis-init.sh
Builds on top of #208 (see last commit to omit unrelated changes)
> Run tests on PHP 7.4 and simplify test matrix and test setup

- README.md
- examples/01-timers.php
- examples/02-periodic.php
- examples/03-ticks.php
- examples/04-signals.php
- examples/11-consume-stdin.php
- examples/12-generate-yes.php
- examples/13-http-client-blocking.php
- examples/14-http-client-async.php
- examples/21-http-server.php
- examples/91-benchmark-ticks.php
- examples/92-benchmark-timers.php
- examples/93-benchmark-ticks-delay.php
- examples/94-benchmark-timers-delay.php
- examples/95-benchmark-memory.php
- src/Factory.php
- src/Loop.php
- tests/LoopTest.php
This topic has come up before in #10, #77, and #82. And their aim was to provide all the pieces in one go, the aim for this PR, and its successors in line, is to discuss all bits in their own PR. As such this PR is providing the bare minimum.
To help that I've made several examples to provide different angles on this topic:
* Full switch over to the new global loop accessor: https://github.com/WyriHaximus/reactphp-cron/pull/51
* Make passing the loop optional, but as the recommended way: https://github.com/clue/reactphp-redis/pull/110
* Fully switch over to the global loop accessor, including setting a new loop for each test: https://github.com/clue/reactphp-redis/pull/109
Resolves: #10 #77 #82
> Global event-loop accessor part four

- README.md
- examples/01-timers.php
- examples/02-periodic.php
- examples/03-ticks.php
- examples/04-signals.php
- examples/11-consume-stdin.php
- examples/12-generate-yes.php
- examples/13-http-client-blocking.php
- examples/14-http-client-async.php
- examples/21-http-server.php
- examples/91-benchmark-ticks.php
- examples/92-benchmark-timers.php
- examples/93-benchmark-ticks-delay.php
- examples/94-benchmark-timers-delay.php
- examples/95-benchmark-memory.php
- src/Loop.php
- tests/LoopTest.php
This changeset adds static Loop methods. The Loop class now provides all methods that exist on the LoopInterface as static methods:
```php
use React\EventLoop\Loop;
// old (still supported)
Loop::get()->addTimer(1.0, fn () => echo 'Tick');
Loop::get()->run();
// new
Loop::addTimer(1.0, fn () => echo 'Tick');
Loop::run();
```
This is particularly useful when directly interfacing with the event loop in application code. I've also updated the documentation to highlight some use cases where the `Loop::get()` method would still be useful when using dependency injection (DI).
Builds on top of #226
> Add static Loop methods

- README.md
- examples/02-periodic.php
- src/Factory.php
This changeset improves documentation regarding deprecated Factory. As of v1.2.0 the `Loop::get()` method should be used instead.
Builds on top of #226
> Improve documentation regarding deprecated Factory

- src/Loop.php
Hi,
I caught a little typo in the docblock of the `Loop::get` method.
Have a nice day.
> Fix typo in docblock

- README.md
- src/ExtEvLoop.php
- src/ExtEventLoop.php
- src/ExtLibevLoop.php
- src/ExtLibeventLoop.php
- src/ExtUvLoop.php
The maintenance for `ExtLibeventLoop` and `ExtLibevLoop` hasn't seen an update since 2013. It's time to move on.
> Mark legacy extensions as deprecated and minor documentation improvements

- README.md
- src/ExtLibeventLoop.php
- src/StreamSelectLoop.php
the readme should not recommend to use the factory anymore but Loop::create
> Minor documentation improvements for references to deprecated `Factory`

- phpunit.xml.dist
- tests/AbstractLoopTest.php
- tests/ExtEventLoopTest.php
- tests/ExtLibeventLoopTest.php
- tests/bin/01-ticks-loop-class.php
- tests/bin/02-ticks-loop-instance.php
- tests/bin/03-ticks-loop-stop.php
- tests/bin/11-uncaught.php
- tests/bin/12-undefined.php
- tests/bin/21-stop.php
- tests/bin/22-stop-uncaught.php
This changeset updates the test suite to declare and validate helper variables (for future PHP 8.2+ compatibility and because these variables may report an `E_DEPRECATED` in tests for PHP 8.1+). This only affects the test suite and is a bit harder to reproduce in this repository itself, but I've stumbled over this while updating ReactPHP's combined test suite that runs all tests of all components and happens to report said `E_DEPRECATED` on PHP 8.1+.
I'll link the downstream PR against this one, a failed test run reported a bunch of these messages:
```
Deprecated: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in /data/vendor/react/event-loop/tests/ExtLibeventLoopTest.php on line 29
```
Builds on top of #238, #232 and …
> Improve test suite to declare and validate helper variables and support running from meta repository (PHP 8.1)

- src/ExtEvLoop.php
- src/ExtLibevLoop.php
- tests/Timer/AbstractTimerTest.php
When initialising a periodic EvTimer, the after and repeat parameters should take the adjusted interval value from Timer. This takes into account any MIN_INTERVAL bounds are applied when initialising the Timer.
Fixes #236
> Fix periodic timer with zero interval for `ExtEvLoop` and legacy `ExtLibevLoop`

- src/StreamSelectLoop.php
- tests/StreamSelectLoopTest.php
This changeset improves the default `StreamSelectLoop` to report any warnings for invalid streams passed to `stream_select()`. The underlying function would report errors if any streams can not be used to watch for any changes.
This can be trivially reproduced by using a stream with any filters attached:
```php
stream_filter_append(STDIN, 'string.rot13');
Loop::addReadStream(STDIN, function () { });
// PHP Warning:  stream_select(): Cannot cast a filtered stream on this system in X on line Y
```
Likewise, this will now report a warning if the underlying file descriptor (FD) number exceeds `FD_SETSIZE` (defaults to `1024` on many platforms). For example, this can be reproduced by running an HTTP benchmark that creates a large number of concurrent connections to a server that allows more …
> Improve default `StreamSelectLoop` to report any warnings for invalid streams passed to `stream_select()`

- src/Timer/Timers.php
This simple changeset improves performance of the `StreamSelectLoop` when no timers are scheduled. This can be reproduced by running the included benchmarks (#100):
```
me@me-mate:~/workspace/reactphp-event-loop$ time php examples/93-benchmark-ticks-delay.php 1000000
// old: 1.8s
// new: 0.5s
```
In a very busy loop constantly using `futureTick()` like this example, this shows a significant improvement. For many "normal" workloads that have any reasonable stream activity, this improvement is expected to be negligible. At the very least, this changeset is expected to offset any negative impact #245 may show, but in some cases you may even be able to see a significant improvement.
The idea behind this PR is to avoid any unnecessary system calls as these incur a significant overhead. In the …
> Improve performance of `StreamSelectLoop` when no timers are scheduled

- .github/workflows/ci.yml
- README.md
- src/ExtEvLoop.php
- src/ExtEventLoop.php
- src/ExtUvLoop.php
- src/StreamSelectLoop.php
I checked and updated the supported PHP versions with the different loop extensions.
Builds on top of #238.
> Update supported PHP versions for loop extensions
